# Generated by Django 3.2 on 2021-11-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_roomsavailable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomsAvailable',
            new_name='Reservation',
        ),
    ]
