# Generated by Django 3.2 on 2021-11-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_roomsavailable_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='booking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_info', to='listings.bookinginfo'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hotel_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room', to='listings.hotelroom'),
        ),
    ]
