# Generated by Django 3.2 on 2021-11-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20211119_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_info',
        ),
    ]
